# -*- coding: utf-8 -*-
"""ML2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14aNPIdhphKVK9ukF_FuxomD90PmZ1qFQ

Machine Learning Bootcamp Day 2 - Printing and Setting Up Python Notebook
"""

print(54321 * 12345);